[config]
schemaVersion = "0.0.1"

[package]
namespace = "Spyci"
name = "SledHeadless"
versionNumber = "1.0.0"
description = "Run Sledding Game as a headless dedicated server: auto-hosts a lobby, keeps it alive and listed, and runs without a display (Docker-ready). NOT FOR PLAYERS."
websiteUrl = "https://github.com/ricky-davis/SGHeadlessServer"
containsNsfwContent = false

[package.dependencies]
LavaGang-MelonLoader = "0.7.3"

[build]
icon = "./images/icon_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "SledHeadless/bin/Release/net6.0/SledHeadless.dll"
target = "/"

[[build.copy]]
source = "CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["sledding-game"]

[publish.categories]
sledding-game = ["tools", "misc"]
